// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_test_03.proto

#ifndef PROTOBUF_pb_5ftest_5f03_2eproto__INCLUDED
#define PROTOBUF_pb_5ftest_5f03_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pb_5ftest_5f03_2eproto();
void protobuf_AssignDesc_pb_5ftest_5f03_2eproto();
void protobuf_ShutdownFile_pb_5ftest_5f03_2eproto();

class S2;
class S1;

// ===================================================================

class S2 : public ::google::protobuf::Message {
 public:
  S2();
  virtual ~S2();

  S2(const S2& from);

  inline S2& operator=(const S2& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2& default_instance();

  void Swap(S2* other);

  // implements Message ----------------------------------------------

  S2* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2& from);
  void MergeFrom(const S2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 s2_a = 1;
  inline bool has_s2_a() const;
  inline void clear_s2_a();
  static const int kS2AFieldNumber = 1;
  inline ::google::protobuf::int32 s2_a() const;
  inline void set_s2_a(::google::protobuf::int32 value);

  // required string s2_b = 2;
  inline bool has_s2_b() const;
  inline void clear_s2_b();
  static const int kS2BFieldNumber = 2;
  inline const ::std::string& s2_b() const;
  inline void set_s2_b(const ::std::string& value);
  inline void set_s2_b(const char* value);
  inline void set_s2_b(const char* value, size_t size);
  inline ::std::string* mutable_s2_b();
  inline ::std::string* release_s2_b();
  inline void set_allocated_s2_b(::std::string* s2_b);

  // @@protoc_insertion_point(class_scope:S2)
 private:
  inline void set_has_s2_a();
  inline void clear_has_s2_a();
  inline void set_has_s2_b();
  inline void clear_has_s2_b();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* s2_b_;
  ::google::protobuf::int32 s2_a_;
  friend void  protobuf_AddDesc_pb_5ftest_5f03_2eproto();
  friend void protobuf_AssignDesc_pb_5ftest_5f03_2eproto();
  friend void protobuf_ShutdownFile_pb_5ftest_5f03_2eproto();

  void InitAsDefaultInstance();
  static S2* default_instance_;
};
// -------------------------------------------------------------------

class S1 : public ::google::protobuf::Message {
 public:
  S1();
  virtual ~S1();

  S1(const S1& from);

  inline S1& operator=(const S1& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S1& default_instance();

  void Swap(S1* other);

  // implements Message ----------------------------------------------

  S1* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S1& from);
  void MergeFrom(const S1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 s1_a = 1 [default = 10];
  inline bool has_s1_a() const;
  inline void clear_s1_a();
  static const int kS1AFieldNumber = 1;
  inline ::google::protobuf::int32 s1_a() const;
  inline void set_s1_a(::google::protobuf::int32 value);

  // optional int32 s1_b = 2 [default = 20];
  inline bool has_s1_b() const;
  inline void clear_s1_b();
  static const int kS1BFieldNumber = 2;
  inline ::google::protobuf::int32 s1_b() const;
  inline void set_s1_b(::google::protobuf::int32 value);

  // repeated .S2 s1_c = 3;
  inline int s1_c_size() const;
  inline void clear_s1_c();
  static const int kS1CFieldNumber = 3;
  inline const ::S2& s1_c(int index) const;
  inline ::S2* mutable_s1_c(int index);
  inline ::S2* add_s1_c();
  inline const ::google::protobuf::RepeatedPtrField< ::S2 >&
      s1_c() const;
  inline ::google::protobuf::RepeatedPtrField< ::S2 >*
      mutable_s1_c();

  // repeated int32 s1_d = 4;
  inline int s1_d_size() const;
  inline void clear_s1_d();
  static const int kS1DFieldNumber = 4;
  inline ::google::protobuf::int32 s1_d(int index) const;
  inline void set_s1_d(int index, ::google::protobuf::int32 value);
  inline void add_s1_d(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      s1_d() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_s1_d();

  // optional int32 s1_e = 5;
  inline bool has_s1_e() const;
  inline void clear_s1_e();
  static const int kS1EFieldNumber = 5;
  inline ::google::protobuf::int32 s1_e() const;
  inline void set_s1_e(::google::protobuf::int32 value);

  // optional int32 s1_f = 6;
  inline bool has_s1_f() const;
  inline void clear_s1_f();
  static const int kS1FFieldNumber = 6;
  inline ::google::protobuf::int32 s1_f() const;
  inline void set_s1_f(::google::protobuf::int32 value);

  // optional int32 s1_g = 7;
  inline bool has_s1_g() const;
  inline void clear_s1_g();
  static const int kS1GFieldNumber = 7;
  inline ::google::protobuf::int32 s1_g() const;
  inline void set_s1_g(::google::protobuf::int32 value);

  // optional int32 s1_h = 8;
  inline bool has_s1_h() const;
  inline void clear_s1_h();
  static const int kS1HFieldNumber = 8;
  inline ::google::protobuf::int32 s1_h() const;
  inline void set_s1_h(::google::protobuf::int32 value);

  // optional int32 s1_i = 9;
  inline bool has_s1_i() const;
  inline void clear_s1_i();
  static const int kS1IFieldNumber = 9;
  inline ::google::protobuf::int32 s1_i() const;
  inline void set_s1_i(::google::protobuf::int32 value);

  // optional int32 s1_j = 10;
  inline bool has_s1_j() const;
  inline void clear_s1_j();
  static const int kS1JFieldNumber = 10;
  inline ::google::protobuf::int32 s1_j() const;
  inline void set_s1_j(::google::protobuf::int32 value);

  // optional int32 s1_k = 11;
  inline bool has_s1_k() const;
  inline void clear_s1_k();
  static const int kS1KFieldNumber = 11;
  inline ::google::protobuf::int32 s1_k() const;
  inline void set_s1_k(::google::protobuf::int32 value);

  // optional int32 s1_l = 12;
  inline bool has_s1_l() const;
  inline void clear_s1_l();
  static const int kS1LFieldNumber = 12;
  inline ::google::protobuf::int32 s1_l() const;
  inline void set_s1_l(::google::protobuf::int32 value);

  // optional int32 s1_m = 13;
  inline bool has_s1_m() const;
  inline void clear_s1_m();
  static const int kS1MFieldNumber = 13;
  inline ::google::protobuf::int32 s1_m() const;
  inline void set_s1_m(::google::protobuf::int32 value);

  // optional int32 s1_n = 14;
  inline bool has_s1_n() const;
  inline void clear_s1_n();
  static const int kS1NFieldNumber = 14;
  inline ::google::protobuf::int32 s1_n() const;
  inline void set_s1_n(::google::protobuf::int32 value);

  // optional int32 s1_o = 15;
  inline bool has_s1_o() const;
  inline void clear_s1_o();
  static const int kS1OFieldNumber = 15;
  inline ::google::protobuf::int32 s1_o() const;
  inline void set_s1_o(::google::protobuf::int32 value);

  // optional int32 s1_p = 16;
  inline bool has_s1_p() const;
  inline void clear_s1_p();
  static const int kS1PFieldNumber = 16;
  inline ::google::protobuf::int32 s1_p() const;
  inline void set_s1_p(::google::protobuf::int32 value);

  // optional int32 s1_q = 17;
  inline bool has_s1_q() const;
  inline void clear_s1_q();
  static const int kS1QFieldNumber = 17;
  inline ::google::protobuf::int32 s1_q() const;
  inline void set_s1_q(::google::protobuf::int32 value);

  // optional int32 s1_r = 18;
  inline bool has_s1_r() const;
  inline void clear_s1_r();
  static const int kS1RFieldNumber = 18;
  inline ::google::protobuf::int32 s1_r() const;
  inline void set_s1_r(::google::protobuf::int32 value);

  // optional int32 s1_s = 19;
  inline bool has_s1_s() const;
  inline void clear_s1_s();
  static const int kS1SFieldNumber = 19;
  inline ::google::protobuf::int32 s1_s() const;
  inline void set_s1_s(::google::protobuf::int32 value);

  // optional int32 s1_t = 20;
  inline bool has_s1_t() const;
  inline void clear_s1_t();
  static const int kS1TFieldNumber = 20;
  inline ::google::protobuf::int32 s1_t() const;
  inline void set_s1_t(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:S1)
 private:
  inline void set_has_s1_a();
  inline void clear_has_s1_a();
  inline void set_has_s1_b();
  inline void clear_has_s1_b();
  inline void set_has_s1_e();
  inline void clear_has_s1_e();
  inline void set_has_s1_f();
  inline void clear_has_s1_f();
  inline void set_has_s1_g();
  inline void clear_has_s1_g();
  inline void set_has_s1_h();
  inline void clear_has_s1_h();
  inline void set_has_s1_i();
  inline void clear_has_s1_i();
  inline void set_has_s1_j();
  inline void clear_has_s1_j();
  inline void set_has_s1_k();
  inline void clear_has_s1_k();
  inline void set_has_s1_l();
  inline void clear_has_s1_l();
  inline void set_has_s1_m();
  inline void clear_has_s1_m();
  inline void set_has_s1_n();
  inline void clear_has_s1_n();
  inline void set_has_s1_o();
  inline void clear_has_s1_o();
  inline void set_has_s1_p();
  inline void clear_has_s1_p();
  inline void set_has_s1_q();
  inline void clear_has_s1_q();
  inline void set_has_s1_r();
  inline void clear_has_s1_r();
  inline void set_has_s1_s();
  inline void clear_has_s1_s();
  inline void set_has_s1_t();
  inline void clear_has_s1_t();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 s1_a_;
  ::google::protobuf::int32 s1_b_;
  ::google::protobuf::RepeatedPtrField< ::S2 > s1_c_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > s1_d_;
  ::google::protobuf::int32 s1_e_;
  ::google::protobuf::int32 s1_f_;
  ::google::protobuf::int32 s1_g_;
  ::google::protobuf::int32 s1_h_;
  ::google::protobuf::int32 s1_i_;
  ::google::protobuf::int32 s1_j_;
  ::google::protobuf::int32 s1_k_;
  ::google::protobuf::int32 s1_l_;
  ::google::protobuf::int32 s1_m_;
  ::google::protobuf::int32 s1_n_;
  ::google::protobuf::int32 s1_o_;
  ::google::protobuf::int32 s1_p_;
  ::google::protobuf::int32 s1_q_;
  ::google::protobuf::int32 s1_r_;
  ::google::protobuf::int32 s1_s_;
  ::google::protobuf::int32 s1_t_;
  friend void  protobuf_AddDesc_pb_5ftest_5f03_2eproto();
  friend void protobuf_AssignDesc_pb_5ftest_5f03_2eproto();
  friend void protobuf_ShutdownFile_pb_5ftest_5f03_2eproto();

  void InitAsDefaultInstance();
  static S1* default_instance_;
};
// ===================================================================


// ===================================================================

// S2

// required int32 s2_a = 1;
inline bool S2::has_s2_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2::set_has_s2_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2::clear_has_s2_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2::clear_s2_a() {
  s2_a_ = 0;
  clear_has_s2_a();
}
inline ::google::protobuf::int32 S2::s2_a() const {
  // @@protoc_insertion_point(field_get:S2.s2_a)
  return s2_a_;
}
inline void S2::set_s2_a(::google::protobuf::int32 value) {
  set_has_s2_a();
  s2_a_ = value;
  // @@protoc_insertion_point(field_set:S2.s2_a)
}

// required string s2_b = 2;
inline bool S2::has_s2_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2::set_has_s2_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2::clear_has_s2_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2::clear_s2_b() {
  if (s2_b_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    s2_b_->clear();
  }
  clear_has_s2_b();
}
inline const ::std::string& S2::s2_b() const {
  // @@protoc_insertion_point(field_get:S2.s2_b)
  return *s2_b_;
}
inline void S2::set_s2_b(const ::std::string& value) {
  set_has_s2_b();
  if (s2_b_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    s2_b_ = new ::std::string;
  }
  s2_b_->assign(value);
  // @@protoc_insertion_point(field_set:S2.s2_b)
}
inline void S2::set_s2_b(const char* value) {
  set_has_s2_b();
  if (s2_b_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    s2_b_ = new ::std::string;
  }
  s2_b_->assign(value);
  // @@protoc_insertion_point(field_set_char:S2.s2_b)
}
inline void S2::set_s2_b(const char* value, size_t size) {
  set_has_s2_b();
  if (s2_b_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    s2_b_ = new ::std::string;
  }
  s2_b_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:S2.s2_b)
}
inline ::std::string* S2::mutable_s2_b() {
  set_has_s2_b();
  if (s2_b_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    s2_b_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:S2.s2_b)
  return s2_b_;
}
inline ::std::string* S2::release_s2_b() {
  clear_has_s2_b();
  if (s2_b_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = s2_b_;
    s2_b_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void S2::set_allocated_s2_b(::std::string* s2_b) {
  if (s2_b_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete s2_b_;
  }
  if (s2_b) {
    set_has_s2_b();
    s2_b_ = s2_b;
  } else {
    clear_has_s2_b();
    s2_b_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:S2.s2_b)
}

// -------------------------------------------------------------------

// S1

// optional int32 s1_a = 1 [default = 10];
inline bool S1::has_s1_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S1::set_has_s1_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S1::clear_has_s1_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S1::clear_s1_a() {
  s1_a_ = 10;
  clear_has_s1_a();
}
inline ::google::protobuf::int32 S1::s1_a() const {
  // @@protoc_insertion_point(field_get:S1.s1_a)
  return s1_a_;
}
inline void S1::set_s1_a(::google::protobuf::int32 value) {
  set_has_s1_a();
  s1_a_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_a)
}

// optional int32 s1_b = 2 [default = 20];
inline bool S1::has_s1_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S1::set_has_s1_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S1::clear_has_s1_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S1::clear_s1_b() {
  s1_b_ = 20;
  clear_has_s1_b();
}
inline ::google::protobuf::int32 S1::s1_b() const {
  // @@protoc_insertion_point(field_get:S1.s1_b)
  return s1_b_;
}
inline void S1::set_s1_b(::google::protobuf::int32 value) {
  set_has_s1_b();
  s1_b_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_b)
}

// repeated .S2 s1_c = 3;
inline int S1::s1_c_size() const {
  return s1_c_.size();
}
inline void S1::clear_s1_c() {
  s1_c_.Clear();
}
inline const ::S2& S1::s1_c(int index) const {
  // @@protoc_insertion_point(field_get:S1.s1_c)
  return s1_c_.Get(index);
}
inline ::S2* S1::mutable_s1_c(int index) {
  // @@protoc_insertion_point(field_mutable:S1.s1_c)
  return s1_c_.Mutable(index);
}
inline ::S2* S1::add_s1_c() {
  // @@protoc_insertion_point(field_add:S1.s1_c)
  return s1_c_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::S2 >&
S1::s1_c() const {
  // @@protoc_insertion_point(field_list:S1.s1_c)
  return s1_c_;
}
inline ::google::protobuf::RepeatedPtrField< ::S2 >*
S1::mutable_s1_c() {
  // @@protoc_insertion_point(field_mutable_list:S1.s1_c)
  return &s1_c_;
}

// repeated int32 s1_d = 4;
inline int S1::s1_d_size() const {
  return s1_d_.size();
}
inline void S1::clear_s1_d() {
  s1_d_.Clear();
}
inline ::google::protobuf::int32 S1::s1_d(int index) const {
  // @@protoc_insertion_point(field_get:S1.s1_d)
  return s1_d_.Get(index);
}
inline void S1::set_s1_d(int index, ::google::protobuf::int32 value) {
  s1_d_.Set(index, value);
  // @@protoc_insertion_point(field_set:S1.s1_d)
}
inline void S1::add_s1_d(::google::protobuf::int32 value) {
  s1_d_.Add(value);
  // @@protoc_insertion_point(field_add:S1.s1_d)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
S1::s1_d() const {
  // @@protoc_insertion_point(field_list:S1.s1_d)
  return s1_d_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
S1::mutable_s1_d() {
  // @@protoc_insertion_point(field_mutable_list:S1.s1_d)
  return &s1_d_;
}

// optional int32 s1_e = 5;
inline bool S1::has_s1_e() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void S1::set_has_s1_e() {
  _has_bits_[0] |= 0x00000010u;
}
inline void S1::clear_has_s1_e() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void S1::clear_s1_e() {
  s1_e_ = 0;
  clear_has_s1_e();
}
inline ::google::protobuf::int32 S1::s1_e() const {
  // @@protoc_insertion_point(field_get:S1.s1_e)
  return s1_e_;
}
inline void S1::set_s1_e(::google::protobuf::int32 value) {
  set_has_s1_e();
  s1_e_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_e)
}

// optional int32 s1_f = 6;
inline bool S1::has_s1_f() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void S1::set_has_s1_f() {
  _has_bits_[0] |= 0x00000020u;
}
inline void S1::clear_has_s1_f() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void S1::clear_s1_f() {
  s1_f_ = 0;
  clear_has_s1_f();
}
inline ::google::protobuf::int32 S1::s1_f() const {
  // @@protoc_insertion_point(field_get:S1.s1_f)
  return s1_f_;
}
inline void S1::set_s1_f(::google::protobuf::int32 value) {
  set_has_s1_f();
  s1_f_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_f)
}

// optional int32 s1_g = 7;
inline bool S1::has_s1_g() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void S1::set_has_s1_g() {
  _has_bits_[0] |= 0x00000040u;
}
inline void S1::clear_has_s1_g() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void S1::clear_s1_g() {
  s1_g_ = 0;
  clear_has_s1_g();
}
inline ::google::protobuf::int32 S1::s1_g() const {
  // @@protoc_insertion_point(field_get:S1.s1_g)
  return s1_g_;
}
inline void S1::set_s1_g(::google::protobuf::int32 value) {
  set_has_s1_g();
  s1_g_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_g)
}

// optional int32 s1_h = 8;
inline bool S1::has_s1_h() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void S1::set_has_s1_h() {
  _has_bits_[0] |= 0x00000080u;
}
inline void S1::clear_has_s1_h() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void S1::clear_s1_h() {
  s1_h_ = 0;
  clear_has_s1_h();
}
inline ::google::protobuf::int32 S1::s1_h() const {
  // @@protoc_insertion_point(field_get:S1.s1_h)
  return s1_h_;
}
inline void S1::set_s1_h(::google::protobuf::int32 value) {
  set_has_s1_h();
  s1_h_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_h)
}

// optional int32 s1_i = 9;
inline bool S1::has_s1_i() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void S1::set_has_s1_i() {
  _has_bits_[0] |= 0x00000100u;
}
inline void S1::clear_has_s1_i() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void S1::clear_s1_i() {
  s1_i_ = 0;
  clear_has_s1_i();
}
inline ::google::protobuf::int32 S1::s1_i() const {
  // @@protoc_insertion_point(field_get:S1.s1_i)
  return s1_i_;
}
inline void S1::set_s1_i(::google::protobuf::int32 value) {
  set_has_s1_i();
  s1_i_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_i)
}

// optional int32 s1_j = 10;
inline bool S1::has_s1_j() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void S1::set_has_s1_j() {
  _has_bits_[0] |= 0x00000200u;
}
inline void S1::clear_has_s1_j() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void S1::clear_s1_j() {
  s1_j_ = 0;
  clear_has_s1_j();
}
inline ::google::protobuf::int32 S1::s1_j() const {
  // @@protoc_insertion_point(field_get:S1.s1_j)
  return s1_j_;
}
inline void S1::set_s1_j(::google::protobuf::int32 value) {
  set_has_s1_j();
  s1_j_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_j)
}

// optional int32 s1_k = 11;
inline bool S1::has_s1_k() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void S1::set_has_s1_k() {
  _has_bits_[0] |= 0x00000400u;
}
inline void S1::clear_has_s1_k() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void S1::clear_s1_k() {
  s1_k_ = 0;
  clear_has_s1_k();
}
inline ::google::protobuf::int32 S1::s1_k() const {
  // @@protoc_insertion_point(field_get:S1.s1_k)
  return s1_k_;
}
inline void S1::set_s1_k(::google::protobuf::int32 value) {
  set_has_s1_k();
  s1_k_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_k)
}

// optional int32 s1_l = 12;
inline bool S1::has_s1_l() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void S1::set_has_s1_l() {
  _has_bits_[0] |= 0x00000800u;
}
inline void S1::clear_has_s1_l() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void S1::clear_s1_l() {
  s1_l_ = 0;
  clear_has_s1_l();
}
inline ::google::protobuf::int32 S1::s1_l() const {
  // @@protoc_insertion_point(field_get:S1.s1_l)
  return s1_l_;
}
inline void S1::set_s1_l(::google::protobuf::int32 value) {
  set_has_s1_l();
  s1_l_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_l)
}

// optional int32 s1_m = 13;
inline bool S1::has_s1_m() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void S1::set_has_s1_m() {
  _has_bits_[0] |= 0x00001000u;
}
inline void S1::clear_has_s1_m() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void S1::clear_s1_m() {
  s1_m_ = 0;
  clear_has_s1_m();
}
inline ::google::protobuf::int32 S1::s1_m() const {
  // @@protoc_insertion_point(field_get:S1.s1_m)
  return s1_m_;
}
inline void S1::set_s1_m(::google::protobuf::int32 value) {
  set_has_s1_m();
  s1_m_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_m)
}

// optional int32 s1_n = 14;
inline bool S1::has_s1_n() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void S1::set_has_s1_n() {
  _has_bits_[0] |= 0x00002000u;
}
inline void S1::clear_has_s1_n() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void S1::clear_s1_n() {
  s1_n_ = 0;
  clear_has_s1_n();
}
inline ::google::protobuf::int32 S1::s1_n() const {
  // @@protoc_insertion_point(field_get:S1.s1_n)
  return s1_n_;
}
inline void S1::set_s1_n(::google::protobuf::int32 value) {
  set_has_s1_n();
  s1_n_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_n)
}

// optional int32 s1_o = 15;
inline bool S1::has_s1_o() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void S1::set_has_s1_o() {
  _has_bits_[0] |= 0x00004000u;
}
inline void S1::clear_has_s1_o() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void S1::clear_s1_o() {
  s1_o_ = 0;
  clear_has_s1_o();
}
inline ::google::protobuf::int32 S1::s1_o() const {
  // @@protoc_insertion_point(field_get:S1.s1_o)
  return s1_o_;
}
inline void S1::set_s1_o(::google::protobuf::int32 value) {
  set_has_s1_o();
  s1_o_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_o)
}

// optional int32 s1_p = 16;
inline bool S1::has_s1_p() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void S1::set_has_s1_p() {
  _has_bits_[0] |= 0x00008000u;
}
inline void S1::clear_has_s1_p() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void S1::clear_s1_p() {
  s1_p_ = 0;
  clear_has_s1_p();
}
inline ::google::protobuf::int32 S1::s1_p() const {
  // @@protoc_insertion_point(field_get:S1.s1_p)
  return s1_p_;
}
inline void S1::set_s1_p(::google::protobuf::int32 value) {
  set_has_s1_p();
  s1_p_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_p)
}

// optional int32 s1_q = 17;
inline bool S1::has_s1_q() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void S1::set_has_s1_q() {
  _has_bits_[0] |= 0x00010000u;
}
inline void S1::clear_has_s1_q() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void S1::clear_s1_q() {
  s1_q_ = 0;
  clear_has_s1_q();
}
inline ::google::protobuf::int32 S1::s1_q() const {
  // @@protoc_insertion_point(field_get:S1.s1_q)
  return s1_q_;
}
inline void S1::set_s1_q(::google::protobuf::int32 value) {
  set_has_s1_q();
  s1_q_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_q)
}

// optional int32 s1_r = 18;
inline bool S1::has_s1_r() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
inline void S1::set_has_s1_r() {
  _has_bits_[0] |= 0x00020000u;
}
inline void S1::clear_has_s1_r() {
  _has_bits_[0] &= ~0x00020000u;
}
inline void S1::clear_s1_r() {
  s1_r_ = 0;
  clear_has_s1_r();
}
inline ::google::protobuf::int32 S1::s1_r() const {
  // @@protoc_insertion_point(field_get:S1.s1_r)
  return s1_r_;
}
inline void S1::set_s1_r(::google::protobuf::int32 value) {
  set_has_s1_r();
  s1_r_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_r)
}

// optional int32 s1_s = 19;
inline bool S1::has_s1_s() const {
  return (_has_bits_[0] & 0x00040000u) != 0;
}
inline void S1::set_has_s1_s() {
  _has_bits_[0] |= 0x00040000u;
}
inline void S1::clear_has_s1_s() {
  _has_bits_[0] &= ~0x00040000u;
}
inline void S1::clear_s1_s() {
  s1_s_ = 0;
  clear_has_s1_s();
}
inline ::google::protobuf::int32 S1::s1_s() const {
  // @@protoc_insertion_point(field_get:S1.s1_s)
  return s1_s_;
}
inline void S1::set_s1_s(::google::protobuf::int32 value) {
  set_has_s1_s();
  s1_s_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_s)
}

// optional int32 s1_t = 20;
inline bool S1::has_s1_t() const {
  return (_has_bits_[0] & 0x00080000u) != 0;
}
inline void S1::set_has_s1_t() {
  _has_bits_[0] |= 0x00080000u;
}
inline void S1::clear_has_s1_t() {
  _has_bits_[0] &= ~0x00080000u;
}
inline void S1::clear_s1_t() {
  s1_t_ = 0;
  clear_has_s1_t();
}
inline ::google::protobuf::int32 S1::s1_t() const {
  // @@protoc_insertion_point(field_get:S1.s1_t)
  return s1_t_;
}
inline void S1::set_s1_t(::google::protobuf::int32 value) {
  set_has_s1_t();
  s1_t_ = value;
  // @@protoc_insertion_point(field_set:S1.s1_t)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pb_5ftest_5f03_2eproto__INCLUDED
