// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_test_04.option.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pb_test_04.option.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {


}  // namespace


void protobuf_AssignDesc_pb_5ftest_5f04_2eoption_2eproto() {
  protobuf_AddDesc_pb_5ftest_5f04_2eoption_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pb_test_04.option.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pb_5ftest_5f04_2eoption_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_pb_5ftest_5f04_2eoption_2eproto() {
}

void protobuf_AddDesc_pb_5ftest_5f04_2eoption_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027pb_test_04.option.proto\032 google/protob"
    "uf/descriptor.proto:6\n\016my_file_option\022\034."
    "google.protobuf.FileOptions\030\320\206\003 \001(\t:<\n\021m"
    "y_message_option\022\037.google.protobuf.Messa"
    "geOptions\030\321\206\003 \001(\005:8\n\017my_field_option\022\035.g"
    "oogle.protobuf.FieldOptions\030\322\206\003 \001(\002:6\n\016m"
    "y_enum_option\022\034.google.protobuf.EnumOpti"
    "ons\030\323\206\003 \001(\010:A\n\024my_enum_value_option\022!.go"
    "ogle.protobuf.EnumValueOptions\030\324\206\003 \001(\r", 358);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pb_test_04.option.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FileOptions::default_instance(),
    50000, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MessageOptions::default_instance(),
    50001, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50002, 2, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::EnumOptions::default_instance(),
    50003, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::EnumValueOptions::default_instance(),
    50004, 13, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pb_5ftest_5f04_2eoption_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pb_5ftest_5f04_2eoption_2eproto {
  StaticDescriptorInitializer_pb_5ftest_5f04_2eoption_2eproto() {
    protobuf_AddDesc_pb_5ftest_5f04_2eoption_2eproto();
  }
} static_descriptor_initializer_pb_5ftest_5f04_2eoption_2eproto_;
const ::std::string my_file_option_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  my_file_option(kMyFileOptionFieldNumber, my_file_option_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  my_message_option(kMyMessageOptionFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< float >, 2, false >
  my_field_option(kMyFieldOptionFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  my_enum_option(kMyEnumOptionFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  my_enum_value_option(kMyEnumValueOptionFieldNumber, 0u);

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
